### ISSUE TITLE
\\の原因について

### ISSUE THREAD

**Issue by eightfx** [ryoya9826/jupyter_lab#1]
1. `assert kazarimozi('Cohen Macaulay', 'textbf') == '\textbf{C}ohen \textbf{M}acaulay'`が引っかかる原因は後半のバックスラッシュが１つなので\tとして解釈されているため。
 `assert kazarimozi('Cohen Macaulay', 'textbf') == '\\textbf{C}ohen \\textbf{M}acaulay'`とすればエラーは解消されるはず。

2. バックスラッシュが２つに見える原因はpythonが\ \という１つの文字として認識しているため。
```
x = "\\",
x 
結果: \\
```
上のようなコードを書くと\ \という１文字が返されるためバックスラッシュが２つあるように見えるが、`print(x)`でちゃんと文字列を出力すれば\は１つに見えるように出力されるし、ファイルなどへの書き込みの際もスラッシュ１つ分として出力されるので実装上は現状のコードで全く問題がないと思う。jupyter notebook等で変数名そのままで結果を出力するなどの正規でない方法を取ると内部状態がそのまま反映されるっぽい。

**Comment by ryoya9826** [comment]
あ，理解しました．
`print(kazarimozi('Cohen Macaulay', 'textbf'))`
をしてみれば想定通りの挙動をしていると一発でわかることでしたね，助かりました．
